/*
 * generated by Xtext 2.14.0
 */
package org.architecture.cnl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ArchitectureCNLStandaloneSetup extends ArchitectureCNLStandaloneSetupGenerated {

	def static void doSetup() {
		new ArchitectureCNLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
