/*
 * generated by Xtext 2.14.0
 */
package org.architecture.cnl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ArchcnlRuntimeModule extends AbstractArchcnlRuntimeModule {
}
