/*
 * generated by Xtext 2.14.0
 */
package org.architecture.cnl.ide


/**
 * Use this class to register ide components.
 */
class ArchitectureCNLIdeModule extends AbstractArchitectureCNLIdeModule {
}
